/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package binimoy;

import java.awt.AWTException;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;



import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.net.Socket;
import java.net.SocketTimeoutException;
import java.sql.SQLException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class ShareScreenPageClient extends javax.swing.JFrame {

    /**
     * Creates new form ShareScreenPageClient
     */

     Socket clientSocket=null;
    DataInputStream din=null;
    DataOutputStream dout=null;
    
    
    JFrame frame;
    JLabel jl;
    void tView(){
        jButton3.setVisible(false);
        Thread tv=new Thread(new Runnable(){

            @Override
            public void run() {
                view_image_data();
            }
            
        });
        tv.start();
    }
    void view_image_data(){
        try {	
		
		//System.out.println("server waiting");
                    //ystem.out.println("server connected");
		int f=0;
                int length=1;
		while(true) {
                    if(!isViewOn) break;
			DataInputStream dIn = new DataInputStream(clientSocket.getInputStream());
			 length = dIn.readInt();  
                        if(length==Info.off) break;
			byte[] message = null;// read length of incoming message
			if(length>0) {
				message = new byte[length];
				dIn.readFully(message, 0, message.length); // read the message
			}
			InputStream iin = new ByteArrayInputStream(message);
			BufferedImage bImageFromConvert = ImageIO.read(iin);
			//		frame.getContentPane().add(new JLabel(new ImageIcon(bImageFromConvert)));
			jl.setIcon(new ImageIcon(bImageFromConvert));
			jl.revalidate();
			   jl.repaint();
			  jl.update(jl.getGraphics());
			frame.pack();
			f=1;
		}
                if(length!=Info.off)dout.writeInt(Info.off);
                else JOptionPane.showMessageDialog(null, "partner offline");

	}catch(Exception ee){

	}
	finally
	{
            
	}
    }
    boolean isViewOn;
    public ShareScreenPageClient(Socket _socket) {
        initComponents();
        isViewOn=true;
        clientSocket=_socket;
        setTitle("ready for screen view");
        if(clientSocket==null) new Cmd("socket null in FileTranspage");
        else{
            try {
                din=new DataInputStream(clientSocket.getInputStream());
                dout=new DataOutputStream(clientSocket.getOutputStream());
            } catch (IOException ex) {
                Logger.getLogger(ChatPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jl=new JLabel();
		jl.setIcon(null);
		 frame = new JFrame("It is your partner Screen");
                frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
		frame.getContentPane().add(jl);
		frame.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("View Screen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 345, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(150, 150, 150)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         try {
             // TODO add your handling code here:
             isViewOn=false;
             dout.writeInt(Info.off);
             dout.flush();
             Thread.sleep(10);
             frame.setVisible(false);
             new FirstPageClient(clientSocket).setVisible(true);
             dispose();
         } catch (Exception ex) {
             Logger.getLogger(ShareScreenPageClient.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // view screen
        
        tView();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareScreenPageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareScreenPageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareScreenPageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareScreenPageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShareScreenPageClient(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
